### ISSUE TITLE
A question, not an issue: output is separate folder with the same structure

### ISSUE THREAD

**Issue by herryswastika** [melihovv/laravel-compile-views#9]
Hi, I also use L5.5. Just a question, can the output is also a folder with the exact structure and filename of the original resource/view folder, but the file is already a compiled version?
The reason is that I use SourceGuardian to temporarily encrypt my code to be deployed to Client, then when everything is done (payment etc), full code will be given.
Thanks

**Comment by melihovv** [comment]
Hello
No, this package cannot do that you want. It simply collects all known views and compile them using laravel View facade.
```
    /**
     * @param string $viewName
     */
    protected function compileView(string $viewName)
    {
        try {
            View::make($viewName)->render();
        } catch (Throwable $e) {
        }
    }
```
You cannot compile views to the same folder structure, because laravel has no support for that. Laravel expects certain structure of compiled views folder.
But, I think, you can change that behavior by register your own class which is responsible for view name -> view path mapping.
